const pesIndieNationalities = {
    // nationalities taken from fminside (fm24)
    "Afghanistan": "Afghan",
    "Albania": "Albanian",
    "Algeria": "Algerian",
    "American Samoa": "American Samoan",
    "Andorra": "Andorran",
    "Angola": "Angola",
    "Anguilla": "Anguillian",
    "Antigua and Barbuda": "Antiguan, Barbudan",
    "Argentina": "Argentinian",
    "Armenia": "Armenia",
    "Aruba": "Aruban",
    "Australia": "Australian",
    "Austria": "Austrian",
    "Azerbaijan": "Azerbaijani",
    "Bahrain": "Bahraini",
    "Bangladesh": "Bangladeshi",
    "Barbados": "Barbadian",
    "Belarus": "Belarusian",
    "Belgium": "Belgian",
    "Belize": "Belizean",
    "Benin": "Beninese",
    "Bermuda": "Bermudian",
    "Bhutan": "Bhutanese",
    "Bolivia": "Bolivian",
    "Bonaire": "Bonairean",
    "Borneo Malay": "Bornean",
    "Bosnia and Herzegovina": "Bosnian",
    "Botswana": "Motswana",
    "Brazil": "Brazilian",
    "British Virgin Islands": "English",
    "Brunei Darussalam": "Bruneian",
    "Bulgaria": "Bulgarian",
    "Burkina Faso": "Burkina Faso",
    "Burma": "Burmese",
    "Burundi": "Burundian",
    "Cambodia": "Cambodian",
    "Cameroon": "Cameroonian",
    "Canada": "Canadian",
    "Cape Verde Islands": "Cape Verde",
    "Cayman Islands": "Caymanian",
    "Central African Republic": "Central African",
    "Chad": "Chadian",
    "Chile": "Chilean",
    "China PR": "China",
    "Chinese Taipei (China PR)": "China",
    "Colombia": "Colombian",
    "Comoros": "Comoran",
    "Congo": "Congo",
    "Cook Islands": "Cook Islander",
    "Costa Rica": "Costa Rican",
    "Croatia": "Croatian",
    "Cuba": "Cuban",
    "Curaçao": "Curaçaoan",
    "Cyprus": "Cyprus",
    "Czech Republic": "Czech",
    "Democratic Republic of Congo": "DR Congo",
    "Denmark": "Danish",
    "Djibouti": "Djibouti",
    "Dominica": "Dominican",
    "Dominican Republic": "Dominican",
    "East Timor": "East Timorese",
    "Ecuador": "Ecuadorian",
    "Egypt": "Egypt",
    "El Salvador": "Salvadoran",
    "England": "English",
    "Equatorial Guinea": "Equatorial Guinea",
    "Eritrea": "Eritrean",
    "Estonia": "Estonia",
    "Ethiopia": "Ethiopian",
    "Faroe Islands": "Faroe Islands",
    "Fiji": "Fijian",
    "Finland": "Finnish",
    "France": "French",
    "French Guiana": "Guianan",
    "Gabon": "Gabon",
    "Georgia": "Georgian",
    "Germany": "German",
    "Ghana": "Ghanian",
    "Gibraltar": "Gibraltar",
    "Great Britain": "English",
    "Greece": "Greek",
    "Grenada": "Grenada",
    "Guadeloupe": "Guadeloupe",
    "Guam": "Guamanian",
    "Guatemala": "Guatemala",
    "Guinea": "Guinea",
    "Guinea-Bissau": "Guinea-Bissau",
    "Guyana": "Guyana",
    "Haiti": "Haitian",
    "Honduras": "Honduran",
    "Hong Kong (China PR)": "China",
    "Hungary": "Hungarian",
    "Iceland": "Icelandic",
    "India": "Indian",
    "Indonesia": "Indonesian",
    "Iran": "Iran",
    "Iraq": "Iraqi",
    "Israel": "Israeli",
    "Italy": "Italian",
    "Ivory Coast": "Ivorian",
    "Jamaica": "Jamaican",
    "Japan": "Japanese",
    "Jordan": "Jordanian",
    "Kazakhstan": "Kazakhstani",
    "Kenya": "Kenyan",
    "Kiribati": "I-Kiribati",
    "Kosovo": "Kosovar",
    "Kuwait": "Kuwaiti",
    "Kyrgyzstan": "Kirghiz",
    "Laos": "Laotian",
    "Latvia": "Latvia",
    "Lebanon": "Lebanese",
    "Lesotho": "Mosotho",
    "Liberia": "Liberia",
    "Libya": "Libya",
    "Liechtenstein": "Liechtensteiner",
    "Lithuania": "Lithuania",
    "Luxembourg": "Luxembourg",
    "Macau (China PR)": "China",
    "Madagascar": "Malagasy",
    "Malawi": "Malawian",
    "Malaysia": "Malaysian",
    "Maldives": "Maldivan",
    "Mali": "Mali",
    "Malta": "Maltese",
    "Martinique": "Martinique",
    "Mauritania": "Mauritanian",
    "Mauritius": "Mauritius",
    "Mayotte": "Mahoran",
    "Mexico": "Mexican",
    "Micronesia": "Micronesian",
    "Moldova": "Moldova",
    "Monaco": "Monegasque",
    "Mongolia": "Mongolian",
    "Montenegro": "Montenegrin",
    "Montserrat": "Montserratian",
    "Morocco": "Moroccan",
    "Mozambique": "Mozambique",
    "Myanmar": "Burmese",
    "Namibia": "Namibia",
    "Nepal": "Nepalese",
    "Netherlands": "Dutch",
    "New Caledonia": "New Caledonian",
    "New Zealand": "New Zealand",
    "Nicaragua": "Nicaraguan",
    "Niger": "Nigerien",
    "Nigeria": "Nigerian",
    "North Korea": "North Korean",
    "North Macedonia": "Macedonian",
    "Northern Ireland": "Northern Irish",
    "Northern Mariana Islands": "American",
    "Norway": "Norwegian",
    "Oman": "Omani",
    "Pakistan": "Pakistani",
    "Palestine": "Palestinian",
    "Panama": "Panama",
    "Papua New Guinea": "Papua New Guinean",
    "Paraguay": "Paraguayan",
    "Pays Basque": "Basque",
    "Peru": "Peruvian",
    "Philippines": "Filipino",
    "Poland": "Polish",
    "Portugal": "Portuguese",
    "Puerto Rico": "Puerto Rican",
    "Qatar": "Qatari",
    "Republic of Ireland": "Irish",
    "Réunion": "Réunionese",
    "Romania": "Romanian",
    "Russia": "Russian",
    "Rwanda": "Rwandan",
    "Saint Barthélemy": "Saint Barthélemy Islander",
    "Saint Kitts and Nevis": "Kittitian or Nevisian",
    "Saint Lucia": "Saint Lucian",
    "Saint Martin": "Saint Martin Islander",
    "Saint Pierre and Miquelon": "Saint-Pierrais, Miquelonnais",
    "Saint Vincent and the Grenadines": "Saint Vincentian",
    "Samoa": "Samoan",
    "San Marino": "Sammarinese",
    "São Tomé and Príncipe": "Sao Tomean",
    "Saudi Arabia": "Saudi Arabia",
    "Scotland": "Scottish",
    "SEA Chinese": "Chinese",
    "Senegal": "Senegal",
    "Serbia": "Serbian",
    "Seychelles": "Seychellois",
    "Sierra Leone": "Sierra Leone",
    "Singapore": "Singaporean",
    "Singh Indian": "Indian",
    "Sint Maarten": "St. Maartener",
    "Slovakia": "Slovak",
    "Slovenia": "Slovenian",
    "Solomon Islands": "Solomon Islander",
    "Somalia": "Somali",
    "South Africa": "South Africa",
    "South Korea": "South Korean",
    "South Sudan": "South Sudanese",
    "South Vietnam": "Vietnamese",
    "Spain": "Spanish",
    "Sri Lanka": "Sri Lankan",
    "Sudan": "Sudanese",
    "Suriname": "Surinamer",
    "Swaziland": "Swazi",
    "Sweden": "Swedish",
    "Switzerland": "Swiss",
    "Syria": "Syrian",
    "Tahiti": "Tahitian",
    "Tajikistan": "Tadzhik",
    "Tanzania": "Tanzanian",
    "Thailand": "Thai",
    "The Bahamas": "Bahamian",
    "The Gambia": "Gambia",
    "Togo": "Togo",
    "Tonga": "Tongan",
    "Trinidad and Tobago": "Trinidadian",
    "Tunisia": "Tunisia",
    "Turkey": "Turkish",
    "Turkmenistan": "Turkmen",
    "Turks and Caicos Islands": "Turks and Caicos Islander",
    "Tuvalu": "Tuvaluan",
    "Uganda": "Ugandan",
    "Ukraine": "Ukrainian",
    "United Arab Emirates": "Emirati",
    "United Kingdom": "English",
    "United States": "American",
    "Uruguay": "Uruguayan",
    "US Virgin Islands": "American Virgin Islander",
    "Uzbekistan": "Uzbekistan",
    "Vanuatu": "Ni-Vanuatu",
    "Venezuela": "Venezuelan",
    "Vietnam": "Vietnamese",
    "Wales": "Welsh",
    "Wallis and Futuna Islands": "Wallisian Futunan",
    "West Germany": "West German",
    "Yemen": "Yemeni",
    "Zambia": "Zambia",
    "Zimbabwe": "Zimbabwean",
    // missing nationalities taken from eafc24
    "Czechia": "Czech",
    "Guernsey": "Guernsey",
    "Holy See": "Holy See",
    "Isle of Man": "Isle of Man",
    "Jersey": "Jersey",
    "Svalbard and Jan Mayen": "Svalbard and Jan Mayen",
    "Türkiye": "Turkish",
    "Åland Islands": "Åland Islands",
    "British Indian Ocean Territory": "English",
    "Chinese Taipei": "China",
    "Christmas Island": "Christmas Island",
    "Cocos (Keeling) Islands": "Cocos (Keeling) Islands",
    "Hong Kong": "China",
    "Korea DPR": "North Korean",
    "Korea Republic": "South Korean",
    "Kyrgyz Republic": "Kyrgyz Republic",
    "Macau": "China",
    "Timor-Leste": "Timor-Leste",
    "Falkland Islands (Malvinas)": "English",
    "Bahamas": "Bahamian",
    "Curacao": "Curacao",
    "Greenland": "Greenland",
    "Saint Martin (French part)": "French",
    "Sint Maarten (Dutch part)": "Dutch",
    "Virgin Islands, British": "English",
    "Virgin Islands, U.S.": "American",
    "Cabo Verde": "Cape Verde",
    "Congo DR": "DR Congo",
    "Côte d'Ivoire": "Ivorian",
    "Eswatini": "Eswatini",
    "Gambia": "Gambia",
    "Saint Helena, Ascension and Tristan da Cunha": "English",
    "Western Sahara": "Western Sahara",
    "Federated States of Micronesia": "Micronesian",
    "French Polynesia": "French",
    "Marshall Islands": "Marshall Islands",
    "Nauru": "Nauru",
    "Niue": "Niue",
    "Norfolk Island": "Norfolk Island",
    "Palau": "Palau",
    "Pitcairn": "Pitcairn",
    "Tokelau": "Tokelau",
    "United States Minor Outlying Islands": "American",
    "Wallis and Futuna": "Wallisian Futunan",
    "Antarctica": "Antarctica",
    "Bouvet Island": "Bouvet Island",
    "French Southern Territories": "French",
    "Heard Island and McDonald Islands": "Australian",
    "South Georgia and the South Sandwich Islands": "Georgian",
    // extracted from efootball 24
    "Central African Rep.": "Central African",
    "China": "China",
    "Ireland": "Irish",
    "Others": "Free Nationality",
    "Republic of Korea": "South Korean",
    "Sao Tome and Principe": "Sao Tome and Principe",
    "St Vincent &amp; Grenadines": "St Vincent & Grenadines",
    "Turks and Caicos Is.": "Turks and Caicos Is.",
    "USA": "American",
}
